defaults:
  - _self_
  - data: iris

model:
  name: log_reg_classifier
  penalty: l2
  dual: False
  tol: 1e-4
  C: 1.0
  fit_intercept: True
  intercept_scaling: 1.0
  solver: "lbfgs"
  max_iter: 100
