defaults:
  - _self_
  - data: iris

model:
  name: catboost_classifier
  random_seed: 63
  iterations: 1000
  learning_rate: 0.03
  l2_leaf_reg: 3
  bagging_temperature: 1
  random_strength: 1
  one_hot_max_size: 2
  leaf_estimation_method: Newton
  silent: True
  allow_writing_files: False

tracking_server:
  experiment_name: iris_classification
  uri: http://localhost:5001/

inference_server:
  uri: http://localhost:5003/
